export { default as Button } from './ui/Button';
export { default as Section } from './ui/Section';
export { default as Container } from './ui/Container';
export { default as Typography } from './ui/Typography';
export { H1, H2, H3, H4, H5, H6, P, Span, Div } from './ui/TextElements';
export { default as ArrovRight } from './ui/ArrovRight';
export { default as CheckIcon } from './ui/CheckIcon';
export { default as LanguageSwitcher } from './ui/LanguageSwitcher';

export { default as AnyWhere } from './sections/AnyWhere';
export { default as AppItegration } from './sections/AppItegration';
export { default as Customization } from './sections/Customization';
export { default as DataSecurity } from './sections/DataSecurity';
export { default as Footer } from './sections/Footer';
export { default as Hero } from './sections/Hero';
export { default as Navbar } from './sections/Navbar';
export { default as Pricing } from './sections/Pricing';
export { default as ProjectManagement } from './sections/ProjectManagement';
export { default as Sponsors } from './sections/Sponsors';
export { default as Testimonials } from './sections/Testimonials';
export { default as Extension } from './sections/Extension';
export { default as WorkTogether } from './sections/WorkTogether';
